export const categoryOptions = [
  "Top Wear",
  "Bottom Wear",
  "Footwear",
  "Innerwear",
  "Winter Wear",
  "Ethnic Wear",
  "Activewear",
  "Sportswear",
  "Sleepwear",
  "Swimwear",
  "Accessories",
  "Plus Size",
  "Maternity Wear",
  "Loungewear",
  "Formal Wear",
  "Casual Wear",
  "Party Wear",
];
